"""Auto-discovers and loads the most recently modified backtest CSV.

Search order:
  1. st.session_state["backtest_data"]  — set by the uploader in fire_dashboard.py
  2. data/BT_*/rolling_msci_strategies_results.csv  — generated by rolling_backtest_suite.py
  3. data/sample/rolling_msci_strategies_results.csv — bundled fallback (tracked in git)
"""
from __future__ import annotations

import glob
import os
import re
from dataclasses import dataclass, field
from typing import IO

import pandas as pd


# Maps primary-asset labels in strategy names to canonical ticker strings.
_LABEL_TO_TICKER: dict[str, str] = {
    "SPY": "SPY",
    "S&P": "SPY",
    "MSCI": "MSCI",
    "IVV": "IVV",
    "QQQ": "QQQ",
}
# Secondary assets assumed in hybrid strategies (order matches percentage string).
_HYBRID_SECONDARY = ["UPRO", "Gold"]


def parse_strategy_allocation(name: str) -> dict[str, float]:
    """
    Derive asset allocation from a strategy name.

    Supported patterns:
      "Hybrid SPY (70/15/15)"   → {SPY: 0.70, UPRO: 0.15, Gold: 0.15}
      "Hybrid MSCI (40/35/25)"  → {MSCI: 0.40, UPRO: 0.35, Gold: 0.25}
      "Dull S&P 500"            → {SPY: 1.0}
      "Dull MSCI World"         → {MSCI: 1.0}
    Falls back to {name: 1.0} for unrecognised patterns.
    """
    if name.lower().startswith("dull"):
        if "msci" in name.lower():
            return {"MSCI": 1.0}
        return {"SPY": 1.0}

    m = re.search(r"Hybrid\s+(\S+)\s+\((\d+(?:/\d+)+)\)", name)
    if m:
        primary_label = m.group(1)
        pcts = [int(p) / 100.0 for p in m.group(2).split("/")]
        total = sum(pcts)
        pcts = [p / total for p in pcts]
        primary_ticker = _LABEL_TO_TICKER.get(primary_label, primary_label)
        assets = [primary_ticker] + _HYBRID_SECONDARY[: len(pcts) - 1]
        return dict(zip(assets, pcts))

    return {name: 1.0}


@dataclass
class BacktestData:
    strategies: list[str]
    cagr_df: pd.DataFrame
    mdd_df: pd.DataFrame
    allocations: dict[str, dict[str, float]] = field(default_factory=dict)


# ── Internal helpers ──────────────────────────────────────────────────────────

def find_csv_on_disk(search_root: str = ".") -> str | None:
    """Return the path to the newest backtest CSV on disk, or None."""
    bt_pattern     = os.path.join(search_root, "data", "BT_*", "rolling_msci_strategies_results.csv")
    sample_pattern = os.path.join(search_root, "data", "sample", "rolling_msci_strategies_results.csv")
    candidates = glob.glob(bt_pattern) + glob.glob(sample_pattern)
    if not candidates:
        return None
    # Prefer generated BT_* folders (more recent) over sample fallback
    bt_candidates = glob.glob(bt_pattern)
    if bt_candidates:
        return max(bt_candidates, key=os.path.getmtime)
    return glob.glob(sample_pattern)[0]


def _parse_dataframe(df: pd.DataFrame, source_name: str) -> tuple[BacktestData, str]:
    """Build BacktestData from an already-loaded DataFrame."""
    cagr_cols = {c: c.replace(" CAGR", "") for c in df.columns if c.endswith(" CAGR")}
    mdd_cols  = {c: c.replace(" MDD", "")  for c in df.columns if c.endswith(" MDD")}
    strategies = list(cagr_cols.values())
    cagr_df = df[[c for c in cagr_cols]].rename(columns=cagr_cols)
    mdd_df  = df[[c for c in mdd_cols]].rename(columns=mdd_cols)
    allocations = {s: parse_strategy_allocation(s) for s in strategies}
    return BacktestData(strategies=strategies, cagr_df=cagr_df, mdd_df=mdd_df, allocations=allocations), source_name


# ── Public API ────────────────────────────────────────────────────────────────

def load_from_uploaded_file(uploaded_file: IO) -> tuple[BacktestData, str]:
    """Parse a Streamlit UploadedFile (or any file-like object) into BacktestData."""
    df = pd.read_csv(uploaded_file, index_col=0, parse_dates=True)
    name = getattr(uploaded_file, "name", "<uploaded>")
    return _parse_dataframe(df, name)


def load_latest_backtest_csv(search_root: str = ".") -> tuple[BacktestData, str] | None:
    """
    Load backtest data. Search order:
      1. st.session_state["backtest_data"]  (uploaded by user via the UI)
      2. data/BT_*/rolling_msci_strategies_results.csv  (generated locally)
      3. data/sample/rolling_msci_strategies_results.csv  (bundled fallback)

    Returns (BacktestData, source_description) or None if nothing is found.
    """
    # 1. Session state (set by the uploader in fire_dashboard.py)
    try:
        import streamlit as st  # noqa: PLC0415
        if "backtest_data" in st.session_state:
            return (
                st.session_state["backtest_data"],
                st.session_state.get("backtest_path", "<uploaded>"),
            )
    except Exception:
        pass

    # 2 & 3. File system
    path = find_csv_on_disk(search_root)
    if path is None:
        return None

    df = pd.read_csv(path, index_col=0, parse_dates=True)
    return _parse_dataframe(df, path)
